# Generated by Django 3.1.2 on 2022-02-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0004_auto_20220201_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
