# Generated by Django 3.1.2 on 2022-02-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0005_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='media',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
