# Generated by Django 3.1.2 on 2022-02-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0006_videos_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='media',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
