# Generated by Django 3.1.2 on 2022-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0008_auto_20220201_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
