# Generated by Django 3.1.2 on 2022-02-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0009_auto_20220201_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
