# Generated by Django 3.1.2 on 2022-02-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0010_auto_20220202_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='videos',
            name='media',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
