# Generated by Django 3.1.2 on 2022-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_frontend', '0011_auto_20220202_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='media',
            field=models.FileField(null=True, upload_to=['/vol/videos', 'videos/'], verbose_name=''),
        ),
    ]
