version: "3.7"
networks:
  ht_container_net: 
    driver: bridge
services:
  web:
    user: root

    container_name: wscontainer
    networks:
      - ht_container_net
    build:
      context: .
    volumes:
      - .:/webserver
      - ./static:/vol/web/static
    environment:
      - DEBUG=0
    command: "bash /scripts/entrypoint.sh"
    depends_on:
      - db
      

  db:
    container_name: dbcontainer
    networks:
      - ht_container_net

    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MrPho1219@

  proxy:
    user: root
    container_name: proxycontainer
    networks:
      - ht_container_net
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 8001:8001
      - 443:443
      - 80:80
    volumes:
      - ./proxy:/etc/nginx/
      - ./static:/vol/static
      - ./media:/vol/media
      - ./frontend/build:/vol/react
    depends_on:
      - web
  ddns:
    container_name: cfcontainer
    image: oznu/cloudflare-ddns:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - API_KEY=Wec2xia8uiDtrXG3UGo15CYGaEu5651G_9wMCM8A
      - ZONE=hdt1996-portfolio.net
      - PROXIED=false

volumes:
  db_vol: 
  static_data:


