version: "3.7"
services:
  web:
    user: root
    container_name: wscontainer
    networks:
      ht_container_net:
          ipv4_address: 172.18.0.4
    build:
      context: .
      dockerfile: ./web_services/Dockerfile
    volumes:
      - ./web_services:/webserver
      - ./data/static:/vol/web/static
      - ./conf/server_config.json:/server_config.json
      - /webserver/media
      - /webserver/static
    environment:
      - DEBUG=1
    command: "/webserver/entrypoint.sh"
    depends_on:
      - db

  db:
    container_name: dbcontainer
    networks:
      ht_container_net:
          ipv4_address: 172.18.0.3
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MrPho1219@

  proxy:
    user: root
    container_name: proxycontainer
    networks:
      ht_container_net:
          ipv4_address: 172.18.0.2
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 8001:8001
      - 443:443
      - 80:80
    volumes:
      - ./proxy:/etc/nginx/
      - ./data/static:/vol/static
      - ./data/media:/vol/media
      - ./web_services/frontend_django/build:/vol/react
    depends_on:
      - web
      
networks:
  ht_container_net: 
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.18.0.1/16
          
volumes:
  static_volume:
  db_vol:

