# Generated by Django 3.1.2 on 2022-03-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20220311_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsongdata',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostsongdata',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
