# Generated by Django 3.2.7 on 2021-12-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_react_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='react_note',
            options={'verbose_name': 'React Note', 'verbose_name_plural': 'React Notes'},
        ),
    ]
