# Generated by Django 3.2.7 on 2021-12-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_react_note_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React_Note',
        ),
    ]
