"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import json
import subprocess
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


server_config = open(os.path.join('/server_config.json'),'r')
conf_dict = json.load(server_config)

#HOST = str(subprocess.run(['hostname', '-i'], capture_output=True, text=True).stdout).replace("\n","",-1)
HOST= conf_dict["host"]
DOMAIN = conf_dict["domain"].replace('https://','')
www = conf_dict["www"].replace('https://','')
server_config.close()

PROJECT_PATH=BASE_DIR

SECRET_KEY=os.environ.get('SECRET_KEY','HDT121919964085')

DEBUG = bool(int(os.environ.get('DEBUG',0)))
ALLOWED_HOSTS = [HOST,DOMAIN,www]
ALLOWED_HOSTS_ENV= os.environ.get('ALLOWED_HOSTS')

if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(','))
DEFAULT_AUTO_FIELD= 'django.db.models.BigAutoField'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps_django.store',
    'apps_django.users',
    'apps_django.spotify',
    'rest_framework',
    'corsheaders',
]

SITE_ID=1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'https://192.168.1.17',
    'https://www.192.168.1.17',
    f'http://{HOST}:8001',
    f'http://{HOST}:3000',
    'http://localhost:3000',
    'http://127.0.0.1:3000'
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "cache-control",
    "credentials",
    "http-access-control-request-method",
]
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_DOMAIN = '.192.168.1.17'
ROOT_URLCONF = 'server_django.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': \
        [
            os.path.join(BASE_DIR,'server_django/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server_django.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'storedb',
        'USER': 'postgres',
        'PASSWORD': 'MrPho1219@',
        'HOST': '172.18.0.3',
        'PORT': '5432',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{'min_length':4}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL='/static/'
STATIC_ROOT='/vol/web/static'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'server_django/static')]
#USER_MEDIA_ROOT = '/vol/web/media'
#USER_MEDIA_URL='/media/'


if DEBUG=="XXX":
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    REACT_ROOT= os.path.join(BASE_DIR,"../web_frontend/frontend_django/build/") 
    REACTSTATIC_ROOT=os.path.join(BASE_DIR,"../web_frontend/frontend_django/build/static")

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.SessionAuthentication'
    ]
}

