"""
Django settings for stockserver project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_PATH=BASE_DIR

CORS_ALLOW_ALL_ORIGINS= True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


SECRET_KEY=os.environ.get('SECRET_KEY','HDT121919964085')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG',0)))
ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS_ENV= os.environ.get('ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(','))

# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stockserver.store',
    'frontend.dj_frontend',
    'API.spotify',
    'rest_framework',
    'corsheaders',
    'stockserver',
]

SITE_ID=1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'stockserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': \
        [
            os.path.join(BASE_DIR,'stockserver/templates'),
            os.path.join(BASE_DIR,'frontend/build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'storedb',
        'USER': 'postgres',
        'PASSWORD': 'password',
        'HOST': '192.168.7.237',
        'PORT': '6432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL='/static/'
""" MEDIA_URL='/media/'
REACT_URL='/react/'
REACTSTATIC_URL='/react/static/' """

STATIC_ROOT='/vol/web/static'
#MEDIA_ROOT='/vol/web/media' Not Needed because in 1st Docker File, media files were copied
"""
REACT_ROOT= "/webserver/frontend/build" Not needed because this directory was binded from webserver in volumes
REACTSTATIC_ROOT="/webserver/frontend/build/static" """ #Not needed because this directory was binded from webserver in volumes

#STATICFILES_DIRS=[os.path.join(BASE_DIR,'frontend/build/static'),]

DEFAULT_AUTO_FIELD= 'django.db.models.BigAutoField'


if DEBUG==1:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    REACT_ROOT= os.path.join(BASE_DIR,"frontend/build/") 
    REACTSTATIC_ROOT=os.path.join(BASE_DIR,"frontend/build/static")

"""     REACTSRC_ROOT= "/webserver/frontend/src" """
"""     REACTSRC_ROOT= os.path.join(BASE_DIR,"frontend/src") """
""" REACTSRC_URL='/react/src/' """
